- name: Local or remote backend selector (remote)
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  when: backend == "true"
  with_items:
    - { src: '{{ playbook_dir }}/roles/terraform/templates/remote-backend-selector.j2', dest: 'roles/terraform/files/remote-backend-selector.tf' }
    - { src: '{{ playbook_dir }}/roles/balancer/templates/remote-backend-selector.j2', dest: 'roles/balancer/files/remote-backend-selector.tf' }
  tags:
    - remote_backend

- name: Local or remote backend selector (local)
  file:
    state: absent
    dest: "{{ item }}"
  when: backend != "true" or backend is undefined
  with_items:
    - roles/terraform/files/remote-backend-selector.tf 
    - roles/balancer/files/remote-backend-selector.tf 
  tags:
    - remote_backend   

- name: Generating variables file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: '{{ playbook_dir }}/roles/terraform/templates/terraform.tfvars.j2', dest: 'roles/terraform/files/terraform.tfvars' }
    - { src: '{{ playbook_dir }}/roles/balancer/templates/terraform.tfvars.j2', dest: 'roles/balancer/files/terraform.tfvars' }
  vars:
    bootnodelbips:
        stdout: '127.0.0.1'
    
- name: Generating backend file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  when: backend == "true"
  with_items:
    - { src: '{{ playbook_dir }}/roles/terraform/templates/backend.tfvars.j2', dest: 'roles/terraform/files/backend.tfvars' }
    - { src: '{{ playbook_dir }}/roles/balancer/templates/backend.tfvars.j2', dest: 'roles/balancer/files/backend.tfvars' }
    
- name: Copy ssh key to terraform directory
  copy: 
    src: "{{ PUB_KEY_STORE }}"
    dest: "{{ item }}"
  with_items:
    - roles/terraform/files/
    - roles/balancer/files/

- name: Terraform destroy balancer
  shell: "echo yes | {{ terraform_location }} {{ item }}"
  args:
    chdir: "roles/balancer/files"
  with_items:
    - "init {{ '-backend-config=backend.tfvars' if backend == 'true' else '' }}"
    - destroy
    
- name: Terraform destroy all infra
  shell: "echo yes | {{ terraform_location }} {{ item }}"
  args:
    chdir: "roles/terraform/files"
  with_items:
    - "init {{ '-backend-config=backend.tfvars' if backend == 'true' else '' }}"
    - destroy