- name: Fetch output folder from moc
  hosts: moc
  tasks:
    - synchronize:
        src: "/home/{{ ansible_user }}/{{ NETWORK_NAME }}" 
        dest: "{{ destination | default ('/tmp/' ~ NETWORK_NAME) }}"
        mode: pull