- name: Generate network variables
  hosts: localhost
  roles:
    - local-preconf
  tags:
    - bootnode
    - moc
    - validator

- name: Prepare infrastructure
  hosts: localhost
  roles:
    - terraform
  tags: 
    - bootnode
    - moc
    - validator

- name: preconf - install python
  hosts: all
  gather_facts: False
  become: True
  tasks:
    - name: Install python
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      
- hosts: all
  tasks:
    - name: Setting remote hosts facts
      set_fact:
        spec_json: "{{ playbook_dir }}/{{ NETWORK_NAME }}/spec.json"
        bootnodes_txt: "{{ playbook_dir }}/{{ NETWORK_NAME }}/bootnodes.txt"
        install_firewall: false
        MOC_ADDRESS: "{{ lookup('file', NETWORK_NAME+'/moc') }}"
        NETSTATS_SERVER: "http://{{ groups['netstat']|first }}:3000"
        NETSTATS_SECRET: "{{ lookup('file', NETWORK_NAME+'/netstat_secret') }}"
        NODE_FULLNAME: "{{ ansible_hostname }}"
  tags: 
    - bootnode
    - moc
    - validator

- name: Launch netstat node
  hosts: netstat
  become: True
  tasks: 
    - include_role:
        name: 'deployment-playbooks/roles/netstat'
      vars:
        username: "netstat"
 
- name: Configure bootnodes
  hosts: bootnode
  become: True
  #serial: 1
  roles:
    - bootnode
  tags:
    - bootnode 
 
- name: Launch explorer node
  hosts: explorer
  become: True
  tasks:
    - include_role:
        name: 'deployment-playbooks/roles/explorer'
      vars:
        username: "explorer"

- name: Configure MoC node
  hosts: moc
  become: True
  roles:
    - moc
  tags: 
    - moc

- name: Restart poa-dashboard on netstat
  hosts: netstat
  become: True
  tasks:
    - name: restart poa-dashboard
      service:
        name: poa-dashboard
        state: restarted
        enabled: yes
    
- name: Cleanup
  hosts: localhost
  tasks:
    - name: Clear /tmp dir
      file:
        state: absent
        path: /tmp/production-keys/*

- name: Prepare prod keys for deployment
  hosts: localhost
  tasks:
    - synchronize: 
        src: "{{ playbook_dir }}/{{ NETWORK_NAME }}/validator-keys/"
        dest: "/tmp/production-keys/"
        mode: pull
  tags:
    - validator

- name: Configure validators node
  hosts: validator
  become: True
  serial: 1
  roles:
    - validator
  tags: 
    - validator
    
- name: Restart poa-netstats on nodes
  hosts: bootnode,moc,validator
  become: True
  tasks:
    - name: restart poa-netstats
      service:
        name: poa-netstats
        state: restarted
        enabled: yes
    
- name: Cleanup
  hosts: localhost
  tasks:
    - name: Clear /tmp dir
      file:
        state: absent
        path: /tmp/production-keys
  
 
        