- name: Check if production keys were not already generated
  local_action:
    module: find
    paths: "{{ playbook_dir }}/{{ NETWORK_NAME }}/validator-keys"
    file_type: directory
  register: folders
  
- name: Clear old MoC installation
  file:
    state: absent
    path: "/home/moc/"
  when: folders.matched == 0

- include_role:
    name: 'deployment-playbooks/roles/moc'
  vars:
    username: "moc"
    MOC_KEYFILE: "{{ lookup('file', NETWORK_NAME+'/moc.json') }}"
    MOC_KEYPASS: "{{ lookup('file', NETWORK_NAME+'/moc_secret') }}"
    GENESIS_NETWORK_NAME: "{{ NETWORK_NAME }}"

- name: Become user moc
  become: true
  become_user: moc
  block:
    - name: Uncomment line at node.toml
      lineinfile:
        path: /home/moc/node.toml
        regexp: '^.*unlock = .*'
        line: 'unlock = ["{{ MOC_ADDRESS }}"]'
      notify:
        - restart poa-parity
        - restart poa-pm2
    
    - name: Run handlers immediately
      meta: flush_handlers
         
    - name: Clone secondary contracts from GitHub
      git:
        repo: "{{ SECONDARY_CONTRACTS_REPO }}"
        dest: "/home/moc/poa-network-consensus-contracts"
        force: yes
    
    - name: Clone production key generator from GitHub
      git:
        repo: "{{ PRODUCTION_KEY_GENERATOR_REPO }}"
        dest: "/home/moc/deployment-terraform"
        force: yes

#   - name: Install required NPM modules
#     npm:
#       path: /home/moc/poa-network-consensus-contracts
#       production: no
#       state: latest

    - name: Install reqired NPM modules (workaround)
      command: npm install
      args:
        chdir: /home/moc/poa-network-consensus-contracts

    - name:  Deploy contracts
      shell: "SAVE_TO_FILE=true POA_NETWORK_CONSENSUS_ADDRESS=0x8bf38d4764929064f2d4d3a56520a76ab3df415b MASTER_OF_CEREMONY={{ MOC_ADDRESS }} ./node_modules/.bin/truffle migrate --reset --network sokol"
      args:
        chdir: /home/moc/poa-network-consensus-contracts
        creates: /home/moc/poa-network-consensus-contracts/contracts.json
 
    - name: Copy contracts.json to local machine
      synchronize: 
        src: "/home/moc/poa-network-consensus-contracts/contracts.json"
        dest: "{{ playbook_dir }}/{{ NETWORK_NAME }}/"
        mode: pull

    - name: Set contracts.json
      block:     
        - slurp:
            src: /home/moc/poa-network-consensus-contracts/contracts.json
          register:
            contracts 
        - set_fact:
            contracts_json: "{{ contracts['content'] | b64decode }}"

    - name: Check if initial keys were not already generated
      find:
        paths: /home/moc/poa-scripts-moc/generateInitialKey/output
      register: initial
        
    - name: Adjust config files before generate initial keys
      lineinfile:
        path: /home/moc/poa-scripts-moc/config.json
        regexp: '^.*\"addr\"\: .*'
        line: '        "addr": "{{ contracts_json.KEYS_MANAGER_ADDRESS }}",'

    - name: Generate initial keys
      shell: "for i in {1..{{ (initial_key_count - initial.matched/2) | int }}}; do npm start; done"
      args:
        chdir: /home/moc/poa-scripts-moc/generateInitialKey
        executable: /bin/bash
      when: initial.matched/2 < initial_key_count
        
    - name: Copy initial keys to the gen-prod-keys folder
      delegate_to: "{{ inventory_hostname }}"
      synchronize:
        src: "/home/moc/poa-scripts-moc/generateInitialKey/output/"
        dest: "/home/moc/deployment-terraform/helper-scripts/gen-prod-keys/keystore"
      when: initial.matched/2 < initial_key_count
    
    - name: Install reqired NPM modules (workaround)
      shell: "npm install"
      args:
        chdir: "/home/moc/deployment-terraform/helper-scripts/gen-prod-keys/"
      when: folders.matched < initial_key_convert_count 
         
    - name: Execute script
      command: "node index.js {{ contracts_json.KEYS_MANAGER_ADDRESS }}"
      args:
        chdir: "/home/moc/deployment-terraform/helper-scripts/gen-prod-keys/"
      when: folders.matched < initial_key_convert_count 
        
    - name: Copy production keys to the destination folder
      synchronize: 
        src: "/home/moc/deployment-terraform/helper-scripts/gen-prod-keys/production-keys/"
        dest: "{{ playbook_dir }}/{{ NETWORK_NAME }}/validator-keys/"
        mode: pull
      when: folders.matched < initial_key_convert_count 

    - name: Comment line at node.toml
      lineinfile:
          path: /home/moc/node.toml
          regexp: '^.*unlock = .*'
          line: '#unlock = ["{{ MOC_ADDRESS }}"]'
      notify:
        - restart poa-parity
        - restart poa-pm2