- name: gather validator address
  local_action: "shell ls /tmp/production-keys/ | sed '1q;d'"
  register: validator

- name: gather list of addresses
  local_action: "shell ls /tmp/production-keys/* | egrep .*mining_.*.json | sed '1q;d' | sed -e 's/^mining_//' -e 's/.json//'"
  register: addresses
    
- name: gather list of keyfiles
  local_action: "shell find /tmp/production-keys/ | egrep .*mining_.*.json | sed '1q;d'"
  register: keyfiles
  
- name: gather list of keys
  local_action: "shell find /tmp/production-keys/ | egrep .*mining_.*.key | sed '1q;d'"
  register: keys

- include_role:
    name: '{{ playbook_dir }}/deployment-playbooks/roles/validator'
  vars:
    username: "validator"
    GENESIS_NETWORK_NAME: "{{ NETWORK_NAME }}"
    MINING_ADDRESS: "{{ addresses.stdout }}"
    MINING_KEYPASS: "{{ lookup ('file', keys.stdout) }}"
    MINING_KEYFILE: "{{ lookup ('file', keyfiles.stdout) }}"
    
- name: iterate
  local_action: "file state=absent path=/tmp/production-keys/{{ validator.stdout }}"