- name: Clearing empty bootnodes.txt
  local_action: 
    module: copy
    dest: "{{ NETWORK_NAME }}/bootnodes.txt" 
    content: ''
    force: yes
    
- name: Ensures certificate directory exists
  file: path=/etc/nginx/ssl/ state=directory
  when: bootnode_balanced_count>0

- name: Place cert at bootnode
  copy:
    src: "./{{ NETWORK_NAME }}/{{ item }}"
    dest: "/etc/nginx/ssl/{{ item }}"
  with_items:
    - server.key
    - server.crt
  when: bootnode_balanced_count>0
 
- include_role:
    name: '{{ playbook_dir }}/deployment-playbooks/roles/bootnode'
  vars:
    username: "bootnode"
    parity_api: "on"
    bootnode_dapps: "on"
    PROXY_PORT: 8545
  notify:
    - restart poa-parity   
    
- name: Run handlers immediately
  meta: flush_handlers

- name: Generate bootnodes.txt
  block:
    - name: Get enode
      uri: 
          url: http://localhost:8545
          method: POST
          body_format: json
          body: '{"method":"parity_enode","params":[],"id":1,"jsonrpc":"2.0"}'
          return_content: yes
          headers: 
            Content-Type: application/json
      register: enode

        
    - name: Adding variable to bootnodes list
      local_action:
        module: lineinfile
        line: "{{ enode.json.result }}"
        path: "{{ playbook_dir }}/{{ NETWORK_NAME }}/bootnodes.txt"
      
- name: Send bootnodes.txt to bootnodes 
  copy:
    src: "{{ NETWORK_NAME }}/bootnodes.txt"
    dest: "/home/bootnode/bootnodes.txt"
    force: true
  notify:
    - restart poa-parity    

- name: Restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
    