---
- hosts: all
  user: poa
  become: True
  roles:
    - preconf
  tags: preconf

- hosts: bootnode
  become: True
  vars:
    nginx_headers: "on"
    PROXY_PORT: "8545"
    username: "bootnode"
    users:
      - name: "bootnode"
    home: "/home/bootnode"
  roles:
    - usermanager
    - nodejs
    - bootnode
    - poa-logrotate
    - poa-parity
    - poa-pm2
    - poa-netstats
    - nginx
    - bootnode-access
  tags:
    - bootnode

- hosts: explorer
  become: True
  vars:
    nginx_headers: "off"
    PROXY_PORT: "3000"
    explorerS_SERVER: "localhost"
    username: "explorer"
    users:
      - name: "explorer"
    home: "/home/explorer"
  roles:
    - usermanager
    - nodejs
    - poa-logrotate
    - poa-parity
    - poa-pm2
    - explorer
    - nginx
    - explorer-access
  tags:
    - explorer
